"""PyTrickle CLI: scaffold starter apps for building streaming pipelines.

Usage:
  pytrickle init my_app --port 8000 --out ./my_app.py [--force]

This generates a minimal, generic template using PyTrickle's decorator handlers
that you can integrate into any pipeline: it wires model loading, video/audio
handlers, a parameter updater, and a stream-stop callback.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from textwrap import dedent
from string import Template as StrTemplate


TEMPLATE = dedent(
    '''
    """Starter streaming app generated by PyTrickle CLI.

    Edit the handlers to integrate your own model or processing pipeline.

    Run:
        python $outfile
    """

    from __future__ import annotations

    import asyncio
    import logging
    from dataclasses import dataclass
    from typing import List


    from pytrickle import StreamProcessor, VideoFrame, AudioFrame
    from pytrickle.decorators import (
        audio_handler,
        model_loader,
        on_stream_stop,
        param_updater,
        video_handler,
    )

    logger = logging.getLogger(__name__)
    logging.basicConfig(level=logging.INFO)


    @dataclass
    class AppConfig:
        enabled: bool = True
        # add your knobs here (e.g., strength: float = 0.5)


    class AppHandlers:
        """Fill in your processing logic inside the handlers below."""

        def __init__(self) -> None:
            self.cfg = AppConfig()
            # initialize your state here (e.g., model = None)

        @model_loader
        async def load(self, **_: dict) -> None:
            """Called once at stream start; load models or warm-up here."""
            logger.info("Model loader: initialize your pipeline here.")

        @video_handler
        async def handle_video(self, frame: VideoFrame) -> VideoFrame:
            """Process or passthrough the incoming video frame."""
            if not self.cfg.enabled:
                return frame

            # Example: passthrough video
            # no-op example; replace with your logic

            return frame

        @audio_handler
        async def handle_audio(self, frame: AudioFrame) -> List[AudioFrame]:
            """Process audio or return as-is."""
            if not self.cfg.enabled:
                return [frame]

            # Example: no-op
            return [frame]

        @param_updater
        async def update_params(self, params: dict) -> None:
            """Update configuration at runtime (via /control endpoint)."""
            if "enabled" in params:
                self.cfg.enabled = bool(params["enabled"])
            # add more params as needed

        @on_stream_stop
        async def on_stop(self) -> None:
            logger.info("Stream stopped; release resources if needed.")


    async def main() -> None:
        handlers = AppHandlers()
        processor = StreamProcessor.from_handlers(
            handlers,
            name="$app_name",
            port=$port,
        )

        # Run the processor event loop until interrupted
        await processor.run_forever()


    if __name__ == "__main__":
        asyncio.run(main())
    '''
).lstrip()


def _write_file(path: Path, content: str, force: bool = False) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"Refusing to overwrite existing file: {path} (use --force)")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def cmd_init(args: argparse.Namespace) -> None:
    app_name = args.name
    port = int(args.port)
    out = Path(args.out)
    if out.is_dir():
        out = out / f"{app_name}.py"

    rendered = StrTemplate(TEMPLATE).safe_substitute(
        app_name=app_name, port=port, outfile=os.fspath(out)
    )
    _write_file(out, rendered, force=bool(args.force))
    print(f"Passthrough template created, run your app with: \033[92mpython {out}\033[0m")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="pytrickle",
        description="PyTrickle CLI",
        epilog=dedent(
            """
            Examples:
              pytrickle init my_app
              pytrickle init my_app --port 9000
              pytrickle init my_app --out ./apps/ --force
            """
        ),
        formatter_class=argparse.RawTextHelpFormatter,
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("init", help="Create a starter app template")
    sp.add_argument("name", help="App name (used in service name and filename if out is a directory)")
    sp.add_argument("--port", type=int, default=8000, help="Port to bind the server (default: 8000)")
    sp.add_argument("--out", default="./", help="Output file or directory (default: current directory)")
    sp.add_argument("--force", action="store_true", help="Overwrite target if exists")
    sp.set_defaults(func=cmd_init)

    return p


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":  # pragma: no cover
    main()
